#!/bin/sh

watchdog_shutdown_hook_handler() {
	status=$1
	module=$2
	if [ "$status" = "pre" ] && [ "$module" = "finish" ]; then
        # Kill watchdog before running systemd. This variable is exported from watchdog module
        [ -n "$INITRAMFS_WATCHDOG_PID" ] && kill "$INITRAMFS_WATCHDOG_PID" || true
	fi
}

watchdog_enabled() {
    [ -c /dev/watchdog ] && return 0 || return 1
}

watchdog_run() {
	add_module_pre_hook "watchdog_shutdown_hook_handler"

    watchdog -t 10 -T 60 -F /dev/watchdog &
    export INITRAMFS_WATCHDOG_PID="$!"
}
